### ISSUE TITLE
World step error

### ISSUE THREAD

**Issue by quinton-ashley** [piqnt/planck.js#266] opened 2023-12-07 03:52 UTC
<img width="485" alt="Screenshot 2023-12-06 at 22 36 51" src="https://github.com/piqnt/planck.js/assets/20031683/6f974b13-9136-4067-82a1-c29547f89cb2">

I'm not sure what the problem is but I can confirm that it's an issue with planck. If I use the version of planck this user had been using before, v1 alpha 4, there's no problems. But then if v1 beta 16 is used, the error occurs.

I don't know what the issue is, but one exceptional thing about this project is the entire game environment exists at all times, there's no section loading, so it makes the world very long, which I understand is not good for performance or accuracy, but nevertheless that's what this creator did.

I've a attached a zip file so you can test out the program yourself.

[sketch1880137 - Dragonz10221.zip](https://github.com/piqnt/planck.js/files/13594709/sketch1880137.-.Dragonz10221.zip)

**Comment by zOadT** [comment] 2023-12-09 10:51
Hey! Thank you for reporting the issue. I did a quick bisect, the bug was introduced by commit `b7ce8be80e6e4c2e71a5d5e3a08aca2676d7c990`. The stack trace is
```
Uncaught TypeError: v is undefined
    transformVec2 Matrix.ts:223
    Distance Distance.ts:173
    testOverlap Distance.ts:749
    update Contact.ts:584
    updateContacts World.ts:977
    step World.ts:809
```
Will take a closer look tomorrow, I guess this should be a relatively easy fix

**Comment by zOadT** [comment] 2023-12-10 11:27
The issue is caused by numeric inaccuracy. It can be solved in `PolygonShape.ts` by replacing
```ts
// (A)
matrix.combineVec2(center, 1, center, triangleArea * k_inv3, e1);
matrix.combineVec2(center, 1, center, triangleArea * k_inv3, e2);
```
with
```ts
center.x += triangleArea * k_inv3 * e1.x + triangleArea * k_inv3 * e2.x;
center.y += triangleArea * k_inv3 * e1.y + triangleArea * k_inv3 * e2.y;
```
It really is just a numeric issue because the issue shows up again if you set
```ts
center.x = center.x + triangleArea * k_inv3 * e1.x + triangleArea * k_inv3 * e2.x;
center.y = center.y + triangleArea * k_inv3 * e1.y + triangleArea * k_inv3 * e2.y;
```
and can be solved again by setting parentheses
```ts
center.x = center.x + (triangleArea * k_inv3 * e1.x + triangleArea * k_inv3 * e2.x);
center.y = center.y + (triangleArea * k_inv3 * e1.y + triangleArea * k_inv3 * e2.y);
```

Could it be that maybe some sizes/masses of bodies are outside of the recommend order of magnitude because they span the entire world?

@shakiba This issue wasn't present in alpha because `(A)` was
```ts
center.addCombine(triangleArea * k_inv3, e1, triangleArea * k_inv3, e2);
```
In general this seems to me to be numerically more stable because the terms being combined are probably the same order of magnitude. Shall we reintroduce a `matrix.addCombineVec2` function and use it where previously `addCombine` was used in the entire code base? But might actually also have to check why this caused an error.

**Comment by shakiba** [comment] 2023-12-10 23:21
Hmm, very interesting—thanks for reporting and investigating this!

How about assigning e1, e2 combination value to a temporary variable and then adding it to center?

**Comment by shakiba** [comment] 2023-12-10 23:31
I was interested to have fewer functions in new matrix, but this seems a common use-case so I think adding a new function as you suggest is also a good idea.

**Comment by shakiba** [comment] 2023-12-11 00:01
One more option is adding combine3Vec2 function, so that we can also use it [here](https://github.com/piqnt/planck.js/blob/820f6105d70f882439c5f0a32f02dbcca54bf95b/src/collision/Distance.ts#L509)

@zOadT Up to you, feel free to do whatever you prefer

**Comment by zOadT** [comment] 2023-12-16 09:21
Oh yeah, `combine3Vec2` is also more similar to the other matrix functions. Will open a PR tomorrow!

**Comment by shakiba** [comment] 2023-12-21 03:50
Is this resolved now?

**Comment by zOadT** [comment] 2023-12-22 17:10
Yes (Sorry, forgot to close it)

**Closed by zOadT** 2023-12-22 17:10 UTC

**Comment by shakiba** [comment] 2023-12-22 19:03
Thanks!

**Comment by quinton-ashley** [comment] 2023-12-22 20:12
@zOadT @shakiba Thank you! Could you guys make a new beta version of planck in dist? or are you waiting to release v1?

**Comment by shakiba** [comment] 2023-12-22 20:13
Yes, I will in a few days, I also merged a few changes

**Comment by quinton-ashley** [comment] 2024-01-08 16:32
@shakiba It worked! Thank you :)
