### ISSUE TITLE
Erroneous Polygon Object collision with Edges

### ISSUE THREAD

**Issue by quinton-ashley** [piqnt/planck.js#222] opened 2022-07-18 23:16 UTC
My student is creating a game in which a shape falls along a path dictated by a line the player creates by clicking. It works really well with circles but with triangles he encountered this glitch. This is a low priority error since he'll just have the player directed object stay a circle but I thought you guys should be aware of it. Here is a video for reference:

https://user-images.githubusercontent.com/20031683/179632484-743d5423-2ed7-4c68-bc69-29acb6ec8493.mov

**Comment by shakiba** [comment] 2023-08-25 06:33
@quinton-ashley Could you please provide some code to reproduce this issue?

Here is an example that works for me: https://piqnt.com/space/dRNv2YJWf

**Comment by quinton-ashley** [comment] 2023-08-25 13:14
That was a video the student sent so I don't have the code, and now it's been a while so I don't remember who it was. I just wanted to pass along the error report. I can try making a demo of the problem though.

**Comment by shakiba** [comment] 2023-08-25 18:42
I see, makes sense. I will close it for now, please feel free to reopen if you are able to reproduce the issue. Thanks!

**Closed by shakiba** 2023-08-25 18:42 UTC
